name: Build & Release on Tagged Commit

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12' 
      - run: python3 make.py
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/random-lyric-update-motd.sh
            dist/random-lyric-update-motd-multiline.sh
            dist/random-lyric-data.json
            dist/random-lyric-data.min.json
            dist/random-lyric-lines.txt
            dist/random-lyric-database.txt
